#
# Dockerfile for shadowsocks-libev
# Source https://github.com/shadowsocks/shadowsocks-libev/blob/master/docker/alpine/Dockerfile
#

FROM alpine
LABEL maintainer="go-ignite" version="3.3.0" org.label-schema.url="https://github.com/go-ignite"

ARG SS_VER=3.3.0
ARG SS_URL=https://github.com/shadowsocks/shadowsocks-libev/releases/download/v$SS_VER/shadowsocks-libev-$SS_VER.tar.gz

RUN set -ex && \
    apk add --no-cache --virtual .build-deps \
                                autoconf \
                                build-base \
                                curl \
                                libev-dev \
                                linux-headers \
                                libsodium-dev \
                                mbedtls-dev \
                                pcre-dev \
                                tar \
                                c-ares-dev && \
    cd /tmp && \
    curl -sSL $SS_URL | tar xz --strip 1 && \
    ./configure --prefix=/usr --disable-documentation && \
    make install && \
    cd .. && \

    runDeps="$( \
        scanelf --needed --nobanner /usr/bin/ss-* \
            | awk '{ gsub(/,/, "\nso:", $2); print "so:" $2 }' \
            | xargs -r apk info --installed \
            | sort -u \
    )" && \
    apk add --no-cache --virtual .run-deps $runDeps && \
    apk del .build-deps && \
    rm -rf /tmp/*

USER nobody

EXPOSE 3389/tcp 3389/udp
ENTRYPOINT ["ss-server","-s","0.0.0.0","-p","3389","--fast-open","-u"]
